name: password_manager_app
description: A Flutter password manager with AES-256 encryption and secure sharing.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.2
  encrypt: ^5.0.3
  local_auth: ^3.0.0
  uuid: ^4.5.0
  share_plus: ^12.0.1
  google_fonts: ^6.2.1
  crypto: ^3.0.3
  cryptography: ^2.5.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
